<?php
	$pwd=$_GET["pwd"];
	if($pwd=="clear"){
		$f=fopen("board.txt","w");
		fwrite($f,"");
		fclose($f);
		$f=fopen("ip.txt","w");
		fwrite($f,"");
		fclose($f);
		sleep(1);
	}
?>
<script>window.location.href="board.php";</script>